name: Release
on:
  workflow_dispatch:
    needs: build

    inputs:
      increase:
        description: "Version increase. Should be 'major', 'minor' or 'patch'"
        required: true
        default: 'patch'

jobs:
  buildTestAndRelease:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout files
       uses: actions/checkout@v2
       with: 
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
     - name: Setup Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         registry-url: 'https://registry.npmjs.org'
         node-version: ${{ matrix.node-version }}
         always-auth: true
     - name: Checkout release branch
       run: | 
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"
        git checkout release
        git pull --squash -s recursive -X theirs origin develop
        git commit -m 'release: squash develop into release'

     - name: Build And Test
       env:
         CI: true
         NPM_TOKEN: ${{ secrets.NPM_READ_TOKEN }}
         NODE_AUTH_TOKEN: ${{ secrets.NPM_READ_TOKEN }}
       run: |
        yarn install --frozen-lockfile --cache --prefer-offline --ignore-scripts --no-progress --non-interactive
        yarn build
        yarn test

     - name: Update version in package.json files
       env:
         NPM_TOKEN: ${{ secrets.NPM_READ_TOKEN }}
       run: |
        node .run.js version ${{ github.event.inputs.increase }}
        git add ./package.json
        git add ./*/package.json
        git commit -m 'release: update package.json files' || echo 'Did not commit any files.'
        git push origin release

     - name: Release packages to NPM
       env:
         NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
         NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
       run: |
         cat <<EOF > .npmrc
           //registry.npmjs.org/:_authToken=${NPM_TOKEN}
           registry=https://registry.npmjs.org
           always-auth=true
         EOF
         node .run.js release
         unlink .npmrc

     - name: Merge changes back to master
       run: |
        git checkout develop
        git pull --squash -s recursive -X theirs origin release
        git commit -m 'release: squashed release back to develop'
        git push origin develop
        git push --tags
